### ISSUE TITLE
Reporting Idle when battery is discharging

### ISSUE THREAD

**Issue by gcoan** [Codegnosis/givtcp-battery-card#30]
**Release with the issue:**
0.2.2

**Browser and Operating System:**
iPadOS Home Assistant Companion app

**Description of problem:**
I have two batteries (on two inverters), identical battery card configurations.

Both batteries were discharging (in Eco mode) but one battery was reported as Idle even though it was clearly discharging 
![image](https://github.com/Codegnosis/givtcp-battery-card/assets/142018870/a22f2879-99e3-41b4-99c3-157f10f06ba6)

It was only when the discharge rate went above 1kW did it start being reported as Discharging
![image](https://github.com/Codegnosis/givtcp-battery-card/assets/142018870/3265db80-d50b-4e7d-aeb8-6a0ac494786f)

I would expect that there needs to be some threshold between reporting Idle and Discharge, recognising that there is the normal in and out that the battery does as the inverter tries to balance demand), but 1kW seems too high to me.
Couldn't see any config to change the behaviour.

Maybe this should be a user config level for the threshold between Idle and Charging/Discharge ?

**Additional information:**
Battery card config:
```
              - type: custom:givtcp-battery-card
                name: G182 Battery
                soc_threshold_very_high: 80
                soc_threshold_high: 60
                soc_threshold_medium: 40
                soc_threshold_low: 20
                soc_threshold_very_high_colour:
                  - 0
                  - 69
                  - 23
                soc_threshold_high_colour:
                  - 67
                  - 160
                  - 71
                soc_threshold_medium_colour:
                  - 255
                  - 166
                  - 0
                soc_threshold_low_colour:
                  - 219
                  - 68
                  - 55
                soc_threshold_very_low_colour:
                  - 94
                  - 0
                  - 0
                display_abs_power: true
                display_type: 2
                display_dp: 1
                icon_status_idle: mdi:sleep
                icon_status_charging: mdi:lightning-bolt
                icon_status_discharging: mdi:home-battery
                display_battery_rates: false
                use_custom_dod: false
                custom_dod: 80
                calculate_reserve_from_dod: true
                display_custom_dod_stats: false
                entity: sensor.g_yyyyy_invertor_serial_number
              - type: custom:givtcp-battery-card
                name: G395 Battery
                soc_threshold_very_high: 80
                soc_threshold_high: 60
                soc_threshold_medium: 40
                soc_threshold_low: 20
                soc_threshold_very_high_colour:
                  - 0
                  - 69
                  - 23
                soc_threshold_high_colour:
                  - 67
                  - 160
                  - 71
                soc_threshold_medium_colour:
                  - 255
                  - 166
                  - 0
                soc_threshold_low_colour:
                  - 219
                  - 68
                  - 55
                soc_threshold_very_low_colour:
                  - 94
                  - 0
                  - 0
                display_abs_power: true
                display_type: 2
                display_dp: 1
                icon_status_idle: mdi:sleep
                icon_status_charging: mdi:lightning-bolt
                icon_status_discharging: mdi:home-battery
                display_battery_rates: false
                use_custom_dod: true
                custom_dod: 80
                calculate_reserve_from_dod: true
                display_custom_dod_stats: false
                entity: sensor.h_xxxx_invertor_serial_number
```
